spring:
  datasource:
    url: jdbc:mysql://localhost:3306/solver?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
         host: smtp.163.com
         username:  13631558898@163.com
         password:  zsp940923
         properties:
            mail:
              smtp:
                auth: true//这样才能通过验证
                starttls:
                    enable: true
                    required: true
